apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring
    spec:
      containers:
      - image: ryancblocker/saffire_springboot_repo_01:latest
        # imagePullPolicy: "Never"
        name: spring
        resources:
          limits:
            cpu: "1"
            memory: "2048Mi"
          requests:
            cpu: "1"
            memory: "2048Mi"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring
  name: spring
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: spring
  type: NodePort
status:
  loadBalancer: {}
