apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: password
  POSTGRES_DB: keycloak
  ADMIN_USER: admin
  ADMIN_PW: admin
